services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
  backend1:
    image: eclipse-temurin:17-jre
    volumes:
      - ./build/libs/be-demo-web-server-0.0.1-SNAPSHOT.jar:/app.jar:ro
    command: java -jar app.jar
  backend2:
    image: eclipse-temurin:17-jre
    volumes:
      - ./build/libs/be-demo-web-server-0.0.1-SNAPSHOT.jar:/app.jar:ro
    command: java -jar app.jar