services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
  backend1:
    image: demo-web-server:1.1
  backend2:
    image: demo-web-server:1.1
